[tool.poetry]
name = "autotrade"
version = "0.1.0"
description = ""
authors = ["thesugar"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.0.1"
numpy = "^1.18.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
